version: '3'

services:
  thumbnailer:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  video-thumbnailer:
    build:
      context: ./videos
      dockerfile: Dockerfile
    network_mode: "service:thumbnailer"
